build_from:
  aarch64: "ghcr.io/hassio-addons/base-python:3.11"
  amd64: "ghcr.io/hassio-addons/base-python:3.11"
  armv7: "ghcr.io/hassio-addons/base-python:3.11"
labels:
  io.hass.version: "1.0.0"
  io.hass.type: "addon"
  io.hass.arch: "aarch64|amd64|armv7"
